# Generated by Django 5.2.9 on 2026-01-06 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_no', models.CharField(max_length=50, unique=True, verbose_name='借用单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('borrowed', '借用中'), ('returned', '已归还'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('borrow_date', models.DateField(verbose_name='借用日期')),
                ('expected_return_date', models.DateField(verbose_name='预计归还日期')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='实际归还日期')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='借用原因')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产借用单',
                'verbose_name_plural': '资产借用单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetBorrowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('is_returned', models.BooleanField(default=False, verbose_name='是否归还')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='归还日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '资产借用明细',
                'verbose_name_plural': '资产借用明细',
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, verbose_name='分类代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('depreciation_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='折旧方式')),
                ('useful_life', models.IntegerField(blank=True, null=True, verbose_name='使用年限(月)')),
                ('salvage_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='残值率(%)')),
                ('custom_fields', models.JSONField(default=list, verbose_name='自定义字段')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': '资产分类',
                'verbose_name_plural': '资产分类',
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_no', models.CharField(max_length=50, unique=True, verbose_name='处置单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('disposal_method', models.CharField(choices=[('scrap', '报废'), ('sell', '出售'), ('donate', '捐赠'), ('transfer_out', '调出'), ('other', '其他')], max_length=20, verbose_name='处置方式')),
                ('disposal_date', models.DateField(verbose_name='处置日期')),
                ('disposal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='处置金额')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='处置原因')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产处置单',
                'verbose_name_plural': '资产处置单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='原值')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='净值')),
                ('disposal_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='处置价值')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '资产处置明细',
                'verbose_name_plural': '资产处置明细',
            },
        ),
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assets/images/', verbose_name='图片')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主图')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资产图片',
                'verbose_name_plural': '资产图片',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('width', models.IntegerField(verbose_name='宽度(mm)')),
                ('height', models.IntegerField(verbose_name='高度(mm)')),
                ('template_config', models.JSONField(default=dict, verbose_name='模板配置')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产标签模板',
                'verbose_name_plural': '资产标签模板',
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_no', models.CharField(max_length=50, unique=True, verbose_name='维保单号')),
                ('maintenance_type', models.CharField(choices=[('repair', '维修'), ('maintain', '保养'), ('upgrade', '升级'), ('other', '其他')], max_length=20, verbose_name='维保类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '处理中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='维保费用')),
                ('service_provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='服务商')),
                ('result', models.TextField(blank=True, null=True, verbose_name='维保结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产维保',
                'verbose_name_plural': '资产维保',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', '录入'), ('update', '编辑'), ('receive', '领用'), ('return', '退还'), ('borrow', '借用'), ('give_back', '归还'), ('transfer', '调拨'), ('change', '变更'), ('maintenance', '维保'), ('dispose', '处置'), ('inventory', '盘点')], max_length=30, verbose_name='操作类型')),
                ('operation_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作单号')),
                ('description', models.TextField(blank=True, null=True, verbose_name='操作描述')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='操作前数据')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='操作后数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '资产操作记录',
                'verbose_name_plural': '资产操作记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_no', models.CharField(max_length=50, unique=True, verbose_name='领用单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('receive_date', models.DateField(verbose_name='领用日期')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='预计归还日期')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='领用原因')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产领用单',
                'verbose_name_plural': '资产领用单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetReceiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '资产领用明细',
                'verbose_name_plural': '资产领用明细',
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(max_length=50, unique=True, verbose_name='调拨单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('transfer_date', models.DateField(verbose_name='调拨日期')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='调拨原因')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产调拨单',
                'verbose_name_plural': '资产调拨单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '资产调拨明细',
                'verbose_name_plural': '资产调拨明细',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=100, verbose_name='资产编码')),
                ('name', models.CharField(max_length=200, verbose_name='资产名称')),
                ('status', models.CharField(choices=[('idle', '闲置'), ('in_use', '在用'), ('borrowed', '借用'), ('maintenance', '维修中'), ('pending_maintenance', '待维修'), ('disposed', '已处置'), ('pending_disposal', '待处置'), ('approving', '审批中')], default='idle', max_length=30, verbose_name='资产状态')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='规格型号')),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='序列号')),
                ('unit', models.CharField(default='台', max_length=20, verbose_name='计量单位')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/images/', verbose_name='资产图片')),
                ('attachments', models.JSONField(default=list, verbose_name='附件列表')),
                ('acquisition_method', models.CharField(choices=[('purchase', '采购'), ('lease', '租赁'), ('gift', '赠予'), ('transfer', '调入'), ('self_build', '自建'), ('other', '其他')], default='purchase', max_length=20, verbose_name='取得方式')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='取得日期')),
                ('original_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='原值')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='净值')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='累计折旧')),
                ('depreciation_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='折旧方式')),
                ('useful_life', models.IntegerField(blank=True, null=True, verbose_name='使用年限(月)')),
                ('salvage_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='残值率(%)')),
                ('depreciation_start_date', models.DateField(blank=True, null=True, verbose_name='折旧开始日期')),
                ('rfid_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='RFID编码')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='条形码')),
                ('qrcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='二维码')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='保修到期日')),
                ('is_component', models.BooleanField(default=False, verbose_name='是否备件')),
                ('custom_data', models.JSONField(default=dict, verbose_name='自定义字段数据')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='organizations.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organizations.location', verbose_name='存放区域')),
                ('manage_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_assets', to='organizations.department', verbose_name='管理部门')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_assets', to=settings.AUTH_USER_MODEL, verbose_name='资产管理员')),
                ('parent_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_assets', to='assets.asset', verbose_name='主资产')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'ordering': ['-created_at'],
            },
        ),
    ]
