# Generated by Django 5.2.9 on 2026-01-06 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('organizations', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='procurement.supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='asset',
            name='using_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='using_assets', to='organizations.department', verbose_name='使用部门'),
        ),
        migrations.AddField(
            model_name='asset',
            name='using_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='using_assets', to=settings.AUTH_USER_MODEL, verbose_name='使用人'),
        ),
        migrations.AddField(
            model_name='assetborrow',
            name='borrow_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_borrows', to='organizations.department', verbose_name='借用部门'),
        ),
        migrations.AddField(
            model_name='assetborrow',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_borrows', to=settings.AUTH_USER_MODEL, verbose_name='借用人'),
        ),
        migrations.AddField(
            model_name='assetborrow',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_borrows', to='organizations.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='assetborrow',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_borrows', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
