# Generated by Django 5.2.9 on 2026-01-06 05:58

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('organizations', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetborrow',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowinstance', verbose_name='审批流程'),
        ),
        migrations.AddField(
            model_name='assetborrowitem',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_items', to='assets.asset', verbose_name='资产'),
        ),
        migrations.AddField(
            model_name='assetborrowitem',
            name='borrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.assetborrow', verbose_name='借用单'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='organizations.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets.assetcategory', verbose_name='上级分类'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetcategory', verbose_name='资产分类'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_disposals', to='organizations.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_disposals', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowinstance', verbose_name='审批流程'),
        ),
        migrations.AddField(
            model_name='assetdisposalitem',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_items', to='assets.asset', verbose_name='资产'),
        ),
        migrations.AddField(
            model_name='assetdisposalitem',
            name='disposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.assetdisposal', verbose_name='处置单'),
        ),
        migrations.AddField(
            model_name='assetimage',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets.asset', verbose_name='资产'),
        ),
        migrations.AddField(
            model_name='assetlabel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_labels', to='organizations.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='assets.asset', verbose_name='资产'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='assetoperation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='assets.asset', verbose_name='资产'),
        ),
        migrations.AddField(
            model_name='assetoperation',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='assetreceive',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_receives', to='organizations.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='assetreceive',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_receives', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='assetreceive',
            name='receive_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_receives', to='organizations.department', verbose_name='领用部门'),
        ),
        migrations.AddField(
            model_name='assetreceive',
            name='receive_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_receives', to=settings.AUTH_USER_MODEL, verbose_name='领用人'),
        ),
        migrations.AddField(
            model_name='assetreceive',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowinstance', verbose_name='审批流程'),
        ),
        migrations.AddField(
            model_name='assetreceiveitem',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_items', to='assets.asset', verbose_name='资产'),
        ),
        migrations.AddField(
            model_name='assetreceiveitem',
            name='receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.assetreceive', verbose_name='领用单'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_transfers', to='organizations.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_transfers', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='from_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_out', to='organizations.department', verbose_name='调出部门'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_out', to='organizations.location', verbose_name='调出位置'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_out', to=settings.AUTH_USER_MODEL, verbose_name='调出人'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='to_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_in', to='organizations.department', verbose_name='调入部门'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_in', to='organizations.location', verbose_name='调入位置'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_in', to=settings.AUTH_USER_MODEL, verbose_name='调入人'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowinstance', verbose_name='审批流程'),
        ),
        migrations.AddField(
            model_name='assettransferitem',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='assets.asset', verbose_name='资产'),
        ),
        migrations.AddField(
            model_name='assettransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.assettransfer', verbose_name='调拨单'),
        ),
        migrations.AlterUniqueTogether(
            name='assetcategory',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('company', 'asset_code')},
        ),
    ]
