# Generated by Django 5.2.9 on 2026-01-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetreceiveitem',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='是否退还'),
        ),
        migrations.AddField(
            model_name='assetreceiveitem',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='退还日期'),
        ),
    ]
