# Generated by Django 5.2.9 on 2026-01-07 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetreceiveitem_is_returned_and_more'),
        ('organizations', '0003_alter_company_dingtalk_corp_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransferitem',
            name='from_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_items_from', to='organizations.department', verbose_name='原部门'),
        ),
        migrations.AddField(
            model_name='assettransferitem',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_items_from', to='organizations.location', verbose_name='原位置'),
        ),
        migrations.AddField(
            model_name='assettransferitem',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_items_from', to=settings.AUTH_USER_MODEL, verbose_name='原使用人'),
        ),
    ]
