# Generated by Django 5.2.9 on 2026-01-06 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('inventory_type', models.CharField(choices=[('full', '全盘'), ('spot', '抽盘'), ('department', '部门盘点'), ('location', '区域盘点')], max_length=20, verbose_name='盘点类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='截止日期')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='实际开始日期')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际完成日期')),
                ('total_assets', models.IntegerField(default=0, verbose_name='应盘数量')),
                ('checked_assets', models.IntegerField(default=0, verbose_name='已盘数量')),
                ('normal_count', models.IntegerField(default=0, verbose_name='盘盈数量')),
                ('loss_count', models.IntegerField(default=0, verbose_name='盘亏数量')),
                ('surplus_count', models.IntegerField(default=0, verbose_name='盘盈数量')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('categories', models.ManyToManyField(blank=True, related_name='inventory_tasks', to='assets.assetcategory', verbose_name='盘点分类')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_tasks', to='organizations.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('departments', models.ManyToManyField(blank=True, related_name='inventory_tasks', to='organizations.department', verbose_name='盘点部门')),
                ('locations', models.ManyToManyField(blank=True, related_name='inventory_tasks', to='organizations.location', verbose_name='盘点区域')),
            ],
            options={
                'verbose_name': '盘点任务',
                'verbose_name_plural': '盘点任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('normal', '正常'), ('loss', '盘亏'), ('surplus', '盘盈'), ('unchecked', '未盘')], default='unchecked', max_length=20, verbose_name='盘点结果')),
                ('check_time', models.DateTimeField(blank=True, null=True, verbose_name='盘点时间')),
                ('images', models.JSONField(default=list, verbose_name='盘点照片')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('actual_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_inventory_records', to='organizations.department', verbose_name='实际部门')),
                ('actual_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_inventory_records', to='organizations.location', verbose_name='实际位置')),
                ('actual_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_inventory_records', to=settings.AUTH_USER_MODEL, verbose_name='实际使用人')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='assets.asset', verbose_name='资产')),
                ('book_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_inventory_records', to='organizations.department', verbose_name='账面部门')),
                ('book_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_inventory_records', to='organizations.location', verbose_name='账面位置')),
                ('book_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_inventory_records', to=settings.AUTH_USER_MODEL, verbose_name='账面使用人')),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_inventory_records', to=settings.AUTH_USER_MODEL, verbose_name='盘点人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inventory.inventorytask', verbose_name='盘点任务')),
            ],
            options={
                'verbose_name': '盘点记录',
                'verbose_name_plural': '盘点记录',
                'unique_together': {('task', 'asset')},
            },
        ),
    ]
