# Generated by Django 5.2.9 on 2026-01-06 05:58

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableInboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金额')),
            ],
            options={
                'verbose_name': '耗材入库明细',
                'verbose_name_plural': '耗材入库明细',
            },
        ),
        migrations.CreateModel(
            name='ConsumableOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_no', models.CharField(max_length=50, unique=True, verbose_name='出库单号')),
                ('outbound_type', models.CharField(choices=[('receive', '领用'), ('return', '退库')], max_length=20, verbose_name='出库类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已出库'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('outbound_date', models.DateField(verbose_name='出库日期')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='领用原因')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '耗材出库单',
                'verbose_name_plural': '耗材出库单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableOutboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '耗材出库明细',
                'verbose_name_plural': '耗材出库明细',
            },
        ),
        migrations.CreateModel(
            name='ConsumableStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '耗材库存',
                'verbose_name_plural': '耗材库存',
            },
        ),
        migrations.CreateModel(
            name='ConsumableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, verbose_name='分类代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_categories', to='organizations.company', verbose_name='所属公司')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='consumables.consumablecategory', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '耗材分类',
                'verbose_name_plural': '耗材分类',
            },
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='耗材编码')),
                ('name', models.CharField(max_length=200, verbose_name='耗材名称')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='规格型号')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='计量单位')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='单价')),
                ('image', models.ImageField(blank=True, null=True, upload_to='consumables/', verbose_name='图片')),
                ('min_stock', models.IntegerField(default=0, verbose_name='最低库存')),
                ('max_stock', models.IntegerField(default=0, verbose_name='最高库存')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='organizations.company', verbose_name='所属公司')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='consumables.consumablecategory', verbose_name='耗材分类')),
            ],
            options={
                'verbose_name': '耗材',
                'verbose_name_plural': '耗材',
            },
        ),
        migrations.CreateModel(
            name='ConsumableInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_no', models.CharField(max_length=50, unique=True, verbose_name='入库单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已入库'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('inbound_date', models.DateField(verbose_name='入库日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='总金额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_inbounds', to='organizations.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '耗材入库单',
                'verbose_name_plural': '耗材入库单',
                'ordering': ['-created_at'],
            },
        ),
    ]
