# Generated by Django 5.2.9 on 2026-01-06 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumables', '0001_initial'),
        ('organizations', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumableinbound',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='consumableinbound',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.location', verbose_name='入库仓库'),
        ),
        migrations.AddField(
            model_name='consumableinbounditem',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumables.consumable', verbose_name='耗材'),
        ),
        migrations.AddField(
            model_name='consumableinbounditem',
            name='inbound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consumables.consumableinbound', verbose_name='入库单'),
        ),
        migrations.AddField(
            model_name='consumableoutbound',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_outbounds', to='organizations.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='consumableoutbound',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consumable_outbounds', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='consumableoutbound',
            name='receive_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.department', verbose_name='领用部门'),
        ),
        migrations.AddField(
            model_name='consumableoutbound',
            name='receive_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_receives', to=settings.AUTH_USER_MODEL, verbose_name='领用人'),
        ),
        migrations.AddField(
            model_name='consumableoutbound',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.location', verbose_name='出库仓库'),
        ),
        migrations.AddField(
            model_name='consumableoutbounditem',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumables.consumable', verbose_name='耗材'),
        ),
        migrations.AddField(
            model_name='consumableoutbounditem',
            name='outbound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consumables.consumableoutbound', verbose_name='出库单'),
        ),
        migrations.AddField(
            model_name='consumablestock',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='consumables.consumable', verbose_name='耗材'),
        ),
        migrations.AddField(
            model_name='consumablestock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_stocks', to='organizations.location', verbose_name='仓库'),
        ),
        migrations.AlterUniqueTogether(
            name='consumablecategory',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='consumable',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='consumablestock',
            unique_together={('consumable', 'warehouse')},
        ),
    ]
