# Generated by Django 5.2.9 on 2026-01-08 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumable',
            options={'verbose_name': '办公用品', 'verbose_name_plural': '办公用品'},
        ),
        migrations.AlterModelOptions(
            name='consumablecategory',
            options={'verbose_name': '用品分类', 'verbose_name_plural': '用品分类'},
        ),
        migrations.AlterModelOptions(
            name='consumableinbound',
            options={'ordering': ['-created_at'], 'verbose_name': '用品入库单', 'verbose_name_plural': '用品入库单'},
        ),
        migrations.AlterModelOptions(
            name='consumableinbounditem',
            options={'verbose_name': '用品入库明细', 'verbose_name_plural': '用品入库明细'},
        ),
        migrations.AlterModelOptions(
            name='consumableoutbound',
            options={'ordering': ['-created_at'], 'verbose_name': '用品出库单', 'verbose_name_plural': '用品出库单'},
        ),
        migrations.AlterModelOptions(
            name='consumableoutbounditem',
            options={'verbose_name': '用品出库明细', 'verbose_name_plural': '用品出库明细'},
        ),
        migrations.AlterModelOptions(
            name='consumablestock',
            options={'verbose_name': '用品库存', 'verbose_name_plural': '用品库存'},
        ),
        migrations.AlterField(
            model_name='consumable',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='consumables.consumablecategory', verbose_name='用品分类'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='code',
            field=models.CharField(max_length=100, verbose_name='用品编码'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supplies/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='min_stock',
            field=models.IntegerField(default=0, verbose_name='安全库存'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='name',
            field=models.CharField(max_length=200, verbose_name='用品名称'),
        ),
        migrations.AlterField(
            model_name='consumableinbounditem',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumables.consumable', verbose_name='用品'),
        ),
        migrations.AlterField(
            model_name='consumableoutbounditem',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumables.consumable', verbose_name='用品'),
        ),
        migrations.AlterField(
            model_name='consumablestock',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='consumables.consumable', verbose_name='用品'),
        ),
    ]
