# Generated by Django 5.2.9 on 2026-01-06 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('start', '开始节点'), ('approval', '审批节点'), ('cc', '抄送节点'), ('condition', '条件节点'), ('end', '结束节点')], max_length=20, verbose_name='节点类型')),
                ('approver_type', models.CharField(blank=True, choices=[('fixed', '指定人员'), ('role', '指定角色'), ('department_manager', '部门主管'), ('superior', '直接上级'), ('self', '发起人自己')], max_length=30, null=True, verbose_name='审批人类型')),
                ('conditions', models.JSONField(default=dict, verbose_name='条件配置')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('approvers', models.ManyToManyField(blank=True, related_name='workflow_nodes', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('next_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_nodes', to='workflows.workflownode', verbose_name='下一节点')),
                ('roles', models.ManyToManyField(blank=True, related_name='workflow_nodes', to='accounts.role', verbose_name='审批角色')),
            ],
            options={
                'verbose_name': '审批节点',
                'verbose_name_plural': '审批节点',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=30, verbose_name='业务类型')),
                ('business_id', models.IntegerField(verbose_name='业务ID')),
                ('business_no', models.CharField(max_length=50, verbose_name='业务单号')),
                ('title', models.CharField(max_length=200, verbose_name='审批标题')),
                ('status', models.CharField(choices=[('pending', '审批中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已撤销')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_instances', to='workflows.workflownode', verbose_name='当前节点')),
            ],
            options={
                'verbose_name': '审批流程实例',
                'verbose_name_plural': '审批流程实例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已拒绝'), ('transferred', '已转交'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflows.workflowinstance', verbose_name='流程实例')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflownode', verbose_name='审批节点')),
            ],
            options={
                'verbose_name': '审批任务',
                'verbose_name_plural': '审批任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('business_type', models.CharField(choices=[('asset_receive', '资产领用'), ('asset_return', '资产退还'), ('asset_borrow', '资产借用'), ('asset_give_back', '资产归还'), ('asset_transfer', '资产调拨'), ('asset_disposal', '资产处置'), ('asset_change', '资产变更'), ('purchase_request', '采购申请'), ('consumable_receive', '耗材领用')], max_length=30, verbose_name='业务类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='organizations.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '审批流程模板',
                'verbose_name_plural': '审批流程模板',
            },
        ),
        migrations.AddField(
            model_name='workflownode',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflowtemplate', verbose_name='流程模板'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='workflows.workflowtemplate', verbose_name='流程模板'),
        ),
    ]
