# Generated by Django 5.2.9 on 2026-01-06 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, verbose_name='模块')),
                ('action', models.CharField(max_length=50, verbose_name='操作')),
                ('content', models.TextField(verbose_name='操作内容')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sys_operation_logs', to='organizations.company', verbose_name='所属公司')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sys_operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('code', models.CharField(max_length=50, verbose_name='规则代码')),
                ('prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='前缀')),
                ('date_format', models.CharField(blank=True, max_length=20, null=True, verbose_name='日期格式')),
                ('serial_length', models.IntegerField(default=4, verbose_name='流水号长度')),
                ('separator', models.CharField(blank=True, max_length=5, null=True, verbose_name='分隔符')),
                ('current_serial', models.IntegerField(default=0, verbose_name='当前流水号')),
                ('reset_cycle', models.CharField(default='never', max_length=20, verbose_name='重置周期')),
                ('last_reset_date', models.DateField(blank=True, null=True, verbose_name='最后重置日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_rules', to='organizations.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '编码规则',
                'verbose_name_plural': '编码规则',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DataDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('code', models.CharField(max_length=50, verbose_name='代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('value', models.CharField(blank=True, max_length=200, null=True, verbose_name='值')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统字典')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_dictionaries', to='organizations.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '数据字典',
                'verbose_name_plural': '数据字典',
                'ordering': ['category', 'sort_order'],
                'unique_together': {('company', 'category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100, verbose_name='配置键')),
                ('config_value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_configs', to='organizations.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'unique_together': {('company', 'config_key')},
            },
        ),
    ]
