# Generated by Django 5.2.9 on 2026-01-07 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, unique=True, verbose_name='模块名称')),
                ('module_label', models.CharField(max_length=100, verbose_name='模块显示名')),
                ('api_base', models.CharField(help_text='如：/api/assets/list/', max_length=200, verbose_name='API基础路径')),
                ('dialog_width', models.CharField(default='900px', max_length=20, verbose_name='弹窗宽度')),
                ('label_width', models.CharField(default='100px', max_length=20, verbose_name='标签宽度')),
                ('enable_create', models.BooleanField(default=True, verbose_name='允许新增')),
                ('enable_edit', models.BooleanField(default=True, verbose_name='允许编辑')),
                ('enable_delete', models.BooleanField(default=True, verbose_name='允许删除')),
                ('enable_import', models.BooleanField(default=True, verbose_name='允许导入')),
                ('enable_export', models.BooleanField(default=True, verbose_name='允许导出')),
                ('extra_config', models.JSONField(blank=True, default=dict, verbose_name='扩展配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模块表单配置',
                'verbose_name_plural': '模块表单配置',
            },
        ),
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=50, verbose_name='模块名称')),
                ('group_key', models.CharField(max_length=50, verbose_name='分组键')),
                ('group_name', models.CharField(max_length=100, verbose_name='分组名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_collapsible', models.BooleanField(default=False, verbose_name='可折叠')),
                ('default_collapsed', models.BooleanField(default=False, verbose_name='默认折叠')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '字段分组',
                'verbose_name_plural': '字段分组',
                'ordering': ['module', 'sort_order'],
                'unique_together': {('module', 'group_key')},
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, help_text='如：asset, consumable, procurement', max_length=50, verbose_name='模块名称')),
                ('field_key', models.CharField(help_text='对应数据库字段名或自定义字段键', max_length=100, verbose_name='字段键')),
                ('field_name', models.CharField(max_length=100, verbose_name='字段名称')),
                ('field_type', models.CharField(choices=[('text', '单行文本'), ('textarea', '多行文本'), ('number', '数字'), ('decimal', '小数'), ('date', '日期'), ('datetime', '日期时间'), ('select', '下拉选择'), ('multi_select', '多选'), ('radio', '单选框'), ('checkbox', '复选框'), ('switch', '开关'), ('reference', '引用查找'), ('tree_select', '树形选择'), ('cascader', '级联选择'), ('image', '图片上传'), ('file', '文件上传'), ('rich_text', '富文本'), ('code', '代码/编号')], default='text', max_length=20, verbose_name='字段类型')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('is_readonly', models.BooleanField(default=False, verbose_name='始终只读')),
                ('is_readonly_on_create', models.BooleanField(default=False, verbose_name='新增时只读')),
                ('is_readonly_on_edit', models.BooleanField(default=False, verbose_name='编辑时只读')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='始终隐藏')),
                ('is_hidden_on_create', models.BooleanField(default=False, verbose_name='新增时隐藏')),
                ('is_hidden_on_edit', models.BooleanField(default=False, verbose_name='编辑时隐藏')),
                ('options', models.JSONField(blank=True, default=list, help_text='格式：[{"label": "显示名", "value": "值"}, ...]', verbose_name='选项列表')),
                ('reference_config', models.JSONField(blank=True, default=dict, help_text='格式：{\n            "api": "/api/path",\n            "labelField": "name",\n            "valueField": "id",\n            "searchField": "name",\n            "multiple": false,\n            "treeData": false,\n            "parentField": "parent_id",\n            "autoFillFields": {"department": "user.department"}\n        }', verbose_name='引用配置')),
                ('number_config', models.JSONField(blank=True, default=dict, help_text='格式：{"min": 0, "max": 999999, "precision": 2, "step": 1}', verbose_name='数字配置')),
                ('code_config', models.JSONField(blank=True, default=dict, help_text='格式：{"prefix": "ZC", "dateFormat": "YYYYMMDD", "length": 8}', verbose_name='编号配置')),
                ('default_value', models.JSONField(blank=True, null=True, verbose_name='默认值')),
                ('validation_rules', models.JSONField(blank=True, default=list, help_text='格式：[\n            {"type": "length", "min": 1, "max": 100, "message": "长度必须在1-100之间"},\n            {"type": "pattern", "pattern": "^[A-Z]+$", "message": "只能输入大写字母"},\n            {"type": "custom", "validator": "validatePhone", "message": "手机号格式不正确"}\n        ]', verbose_name='验证规则')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='占位符')),
                ('help_text', models.CharField(blank=True, max_length=500, verbose_name='帮助文本')),
                ('width', models.IntegerField(default=8, help_text='栅格宽度，1-24，默认8表示一行3列', verbose_name='宽度')),
                ('show_in_list', models.BooleanField(default=False, verbose_name='列表中显示')),
                ('list_width', models.IntegerField(default=150, verbose_name='列表列宽')),
                ('list_sortable', models.BooleanField(default=False, verbose_name='列表可排序')),
                ('list_searchable', models.BooleanField(default=False, verbose_name='列表可搜索')),
                ('is_system', models.BooleanField(default=False, help_text='系统字段不允许删除', verbose_name='系统字段')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='其他自定义配置', verbose_name='扩展配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='system.fieldgroup', verbose_name='所属分组')),
            ],
            options={
                'verbose_name': '字段定义',
                'verbose_name_plural': '字段定义',
                'ordering': ['module', 'group__sort_order', 'sort_order'],
                'unique_together': {('module', 'field_key')},
            },
        ),
    ]
