# Generated by Django 5.2.9 on 2026-01-09 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_company_company_type_company_currency_and_more'),
        ('system', '0002_add_form_config_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderule',
            name='company',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级规则', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_rules', to='organizations.company', verbose_name='所属公司'),
        ),
    ]
