# Generated by Django 5.2.9 on 2026-01-09 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_company_company_type_company_currency_and_more'),
        ('system', '0003_alter_coderule_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddefinition',
            name='formula_config',
            field=models.JSONField(blank=True, default=dict, help_text='格式：{\n            "expression": "price * quantity",\n            "depends_on": ["price", "quantity"],\n            "precision": 2,\n            "format": "currency"\n        }', verbose_name='公式配置'),
        ),
        migrations.AlterField(
            model_name='fielddefinition',
            name='field_type',
            field=models.CharField(choices=[('text', '单行文本'), ('textarea', '多行文本'), ('number', '数字'), ('decimal', '小数'), ('date', '日期'), ('datetime', '日期时间'), ('select', '下拉选择'), ('multi_select', '多选'), ('radio', '单选框'), ('checkbox', '复选框'), ('switch', '开关'), ('reference', '引用查找'), ('tree_select', '树形选择'), ('cascader', '级联选择'), ('image', '图片上传'), ('file', '文件上传'), ('rich_text', '富文本'), ('code', '代码/编号'), ('formula', '公式计算'), ('expression', '条件表达式')], default='text', max_length=20, verbose_name='字段类型'),
        ),
        migrations.CreateModel(
            name='FormLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, help_text='如：asset, consumable, asset_receive', max_length=50, verbose_name='模块名称')),
                ('layout_type', models.CharField(choices=[('form', '表单布局'), ('detail', '详情布局'), ('list', '列表布局')], default='form', max_length=20, verbose_name='布局类型')),
                ('layout_name', models.CharField(blank=True, help_text='用于区分同一模块的多种布局（如移动端/PC端）', max_length=100, verbose_name='布局名称')),
                ('layout_config', models.JSONField(default=dict, help_text='JSON 结构示例：\n        {\n            "rows": [\n                {\n                    "id": "row_1",\n                    "cols": [\n                        {"span": 12, "field": "asset_code"},\n                        {"span": 12, "field": "name"}\n                    ]\n                },\n                {\n                    "id": "row_2",\n                    "cols": [\n                        {"span": 24, "field": "description"}\n                    ]\n                }\n            ],\n            "groups": [\n                {\n                    "id": "group_finance",\n                    "title": "财务信息",\n                    "collapsed": false,\n                    "rows": [...]\n                }\n            ]\n        }', verbose_name='布局配置')),
                ('is_default', models.BooleanField(default=False, help_text='同类型下只有一个默认布局', verbose_name='默认布局')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(blank=True, help_text='为空表示全局默认布局', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_layouts', to='organizations.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_form_layouts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '表单布局',
                'verbose_name_plural': '表单布局',
                'ordering': ['module', 'layout_type', '-is_default'],
                'unique_together': {('module', 'layout_type', 'company', 'layout_name')},
            },
        ),
    ]
