# Generated by Django 5.2.9 on 2026-01-06 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('alert_type', models.CharField(choices=[('warranty_expiry', '保修到期'), ('contract_expiry', '合同到期'), ('stock_low', '库存不足'), ('maintenance_due', '维保到期'), ('return_due', '借用归还')], max_length=30, verbose_name='预警类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('advance_days', models.IntegerField(default=7, verbose_name='提前天数')),
                ('repeat_interval', models.IntegerField(default=1, verbose_name='重复间隔(天)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='organizations.company', verbose_name='所属公司')),
                ('recipients', models.ManyToManyField(blank=True, related_name='alert_rules', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
            ],
            options={
                'verbose_name': '预警规则',
                'verbose_name_plural': '预警规则',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('is_published', models.BooleanField(default=False, verbose_name='已发布')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='organizations.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-is_top', '-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('system', '系统通知'), ('workflow', '审批通知'), ('alert', '预警提醒'), ('announcement', '公告')], max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('business_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='业务类型')),
                ('business_id', models.IntegerField(blank=True, null=True, verbose_name='业务ID')),
                ('is_global', models.BooleanField(default=False, verbose_name='全局通知')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organizations.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_records', to='notifications.notification', verbose_name='通知')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知接收记录',
                'verbose_name_plural': '通知接收记录',
                'unique_together': {('notification', 'user')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(related_name='received_notifications', through='notifications.NotificationRecipient', to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
        ),
    ]
