# Generated by Django 5.2.9 on 2026-01-06 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_no', models.CharField(max_length=50, unique=True, verbose_name='入账单号')),
                ('status', models.CharField(choices=[('pending', '待入账'), ('accounted', '已入账'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('accounting_date', models.DateField(verbose_name='入账日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='总金额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_accountings', to='organizations.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '资产入账',
                'verbose_name_plural': '资产入账',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='方案名称')),
                ('method', models.CharField(choices=[('straight_line', '直线法'), ('declining_balance', '双倍余额递减法'), ('sum_of_years', '年数总和法'), ('units_of_production', '工作量法')], max_length=30, verbose_name='折旧方法')),
                ('useful_life', models.IntegerField(verbose_name='使用年限(月)')),
                ('salvage_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='残值率(%)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认方案')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_schemes', to='organizations.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '折旧方案',
                'verbose_name_plural': '折旧方案',
            },
        ),
        migrations.CreateModel(
            name='AssetLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='原值')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='累计折旧')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='净值')),
                ('impairment', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='减值准备')),
                ('depreciation_start_date', models.DateField(blank=True, null=True, verbose_name='折旧开始日期')),
                ('remaining_months', models.IntegerField(default=0, verbose_name='剩余折旧月数')),
                ('last_depreciation_date', models.DateField(blank=True, null=True, verbose_name='最后折旧日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='assets.asset', verbose_name='资产')),
                ('depreciation_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.depreciationscheme', verbose_name='折旧方案')),
            ],
            options={
                'verbose_name': '资产财务台账',
                'verbose_name_plural': '资产财务台账',
            },
        ),
        migrations.CreateModel(
            name='AssetAccountingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='原值')),
                ('accounting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.assetaccounting', verbose_name='入账单')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='资产')),
                ('depreciation_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.depreciationscheme', verbose_name='折旧方案')),
            ],
            options={
                'verbose_name': '资产入账明细',
                'verbose_name_plural': '资产入账明细',
            },
        ),
        migrations.CreateModel(
            name='DepreciationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10, verbose_name='折旧期间')),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='本期折旧额')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='累计折旧')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='当前净值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='assets.asset', verbose_name='资产')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='organizations.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '折旧记录',
                'verbose_name_plural': '折旧记录',
                'ordering': ['-period'],
                'unique_together': {('asset', 'period')},
            },
        ),
    ]
