# Generated by Django 5.2.9 on 2026-01-06 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('wework', '企业微信'), ('dingtalk', '钉钉'), ('feishu', '飞书')], max_length=20, verbose_name='SSO平台')),
                ('app_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='应用ID')),
                ('app_secret', models.CharField(blank=True, max_length=200, null=True, verbose_name='应用密钥')),
                ('extra_config', models.JSONField(blank=True, default=dict, verbose_name='扩展配置')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('auto_sync', models.BooleanField(default=True, verbose_name='自动同步')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_configs', to='organizations.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': 'SSO配置',
                'verbose_name_plural': 'SSO配置',
                'unique_together': {('company', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='SSOSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('department', '部门同步'), ('user', '用户同步'), ('full', '全量同步')], max_length=20, verbose_name='同步类型')),
                ('status', models.CharField(choices=[('running', '同步中'), ('success', '成功'), ('failed', '失败')], default='running', max_length=20, verbose_name='状态')),
                ('total_count', models.IntegerField(default=0, verbose_name='总数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('detail', models.JSONField(default=dict, verbose_name='详细信息')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('sso_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='sso.ssoconfig', verbose_name='SSO配置')),
            ],
            options={
                'verbose_name': 'SSO同步日志',
                'verbose_name_plural': 'SSO同步日志',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SSOUserBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('wework', '企业微信'), ('dingtalk', '钉钉'), ('feishu', '飞书')], max_length=20, verbose_name='SSO平台')),
                ('provider_user_id', models.CharField(max_length=200, verbose_name='平台用户ID')),
                ('provider_user_info', models.JSONField(blank=True, default=dict, verbose_name='平台用户信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_bindings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'SSO用户绑定',
                'verbose_name_plural': 'SSO用户绑定',
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
