# Generated by Django 5.2.9 on 2026-01-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssoconfig',
            name='app_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='应用ID'),
        ),
    ]
