# Generated by Django 5.2.9 on 2026-01-08 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_company_company_type_company_currency_and_more'),
        ('sso', '0002_alter_ssoconfig_app_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ssouserbinding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ssoconfig',
            name='agent_id',
            field=models.CharField(blank=True, help_text='自建应用AgentID', max_length=200, null=True, verbose_name='应用AgentID'),
        ),
        migrations.AddField(
            model_name='ssoconfig',
            name='auto_create_department',
            field=models.BooleanField(default=True, help_text='同步时自动创建缺失的部门', verbose_name='自动创建部门'),
        ),
        migrations.AddField(
            model_name='ssoconfig',
            name='auto_create_user',
            field=models.BooleanField(default=True, help_text='SSO登录时自动创建用户', verbose_name='自动创建用户'),
        ),
        migrations.AddField(
            model_name='ssoconfig',
            name='callback_url',
            field=models.URLField(blank=True, help_text='OAuth回调地址', null=True, verbose_name='回调地址'),
        ),
        migrations.AddField(
            model_name='ssoconfig',
            name='corp_id',
            field=models.CharField(blank=True, help_text='企业微信CorpID / 钉钉CorpID / 飞书CorpID', max_length=200, null=True, verbose_name='企业ID'),
        ),
        migrations.AddField(
            model_name='ssoconfig',
            name='default_role_id',
            field=models.IntegerField(blank=True, help_text='SSO创建的用户默认分配的角色', null=True, verbose_name='新用户默认角色ID'),
        ),
        migrations.AddField(
            model_name='ssoconfig',
            name='oauth_enabled',
            field=models.BooleanField(default=True, verbose_name='启用OAuth登录'),
        ),
        migrations.AddField(
            model_name='ssoconfig',
            name='root_department_id',
            field=models.CharField(blank=True, help_text='只同步该部门及其子部门，为空则同步全部', max_length=50, null=True, verbose_name='同步根部门ID'),
        ),
        migrations.AddField(
            model_name='ssoconfig',
            name='sync_departments',
            field=models.BooleanField(default=True, verbose_name='同步部门'),
        ),
        migrations.AddField(
            model_name='ssoconfig',
            name='sync_enabled',
            field=models.BooleanField(default=True, verbose_name='启用数据同步'),
        ),
        migrations.AddField(
            model_name='ssoconfig',
            name='sync_interval',
            field=models.IntegerField(default=60, help_text='自动同步间隔，0表示禁用自动同步', verbose_name='同步间隔(分钟)'),
        ),
        migrations.AddField(
            model_name='ssoconfig',
            name='sync_users',
            field=models.BooleanField(default=True, verbose_name='同步用户'),
        ),
        migrations.AddField(
            model_name='ssouserbinding',
            name='company',
            field=models.ForeignKey(blank=True, help_text='关联的公司，支持多公司用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sso_user_bindings', to='organizations.company', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='ssouserbinding',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='ssouserbinding',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='app_secret',
            field=models.CharField(blank=True, help_text='应用密钥，建议加密存储', max_length=500, null=True, verbose_name='应用密钥'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict, help_text='存储特定平台的额外配置', verbose_name='扩展配置'),
        ),
        migrations.AlterField(
            model_name='ssouserbinding',
            name='provider_user_info',
            field=models.JSONField(blank=True, default=dict, help_text='存储从SSO平台获取的用户原始信息', verbose_name='平台用户信息'),
        ),
        migrations.AlterUniqueTogether(
            name='ssouserbinding',
            unique_together={('company', 'provider', 'provider_user_id')},
        ),
    ]
