# Generated by Django 5.2.9 on 2026-01-06 05:58

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='工号')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='职位')),
                ('sso_type', models.CharField(choices=[('none', '无'), ('wework', '企业微信'), ('dingtalk', '钉钉'), ('feishu', '飞书')], default='none', max_length=20, verbose_name='SSO类型')),
                ('sso_user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='SSO用户ID')),
                ('wework_user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='企业微信UserID')),
                ('dingtalk_user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='钉钉UserID')),
                ('feishu_user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='飞书UserID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('import', '导入'), ('export', '导出'), ('approve', '审批'), ('other', '其他')], max_length=20, verbose_name='操作类型')),
                ('module', models.CharField(max_length=50, verbose_name='功能模块')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('request_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='请求路径')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='请求方法')),
                ('request_body', models.JSONField(blank=True, null=True, verbose_name='请求内容')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='角色代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='角色描述')),
                ('permissions', models.JSONField(default=dict, verbose_name='权限配置')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
            },
        ),
    ]
