# Generated by Django 5.2.9 on 2026-01-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dingtalk_user_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='钉钉UserID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='feishu_user_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='飞书UserID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sso_user_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SSO用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wework_user_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='企业微信UserID'),
        ),
    ]
