# Generated by Django 5.2.9 on 2026-01-08 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_avatar_alter_user_position'),
        ('organizations', '0003_alter_company_dingtalk_corp_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('primary', '主公司'), ('secondary', '兼职公司'), ('temporary', '临时借调')], default='primary', max_length=20, verbose_name='关联类型')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否公司管理员')),
                ('can_view_finance', models.BooleanField(default=False, verbose_name='可查看财务数据')),
                ('data_scope', models.CharField(choices=[('all', '全公司'), ('department', '本部门'), ('self', '仅自己')], default='self', max_length=20, verbose_name='数据范围')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='生效日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户公司关联',
                'verbose_name_plural': '用户公司关联',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='company',
            field=models.ForeignKey(blank=True, help_text='全局角色无需关联公司', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='role',
            name='scope',
            field=models.CharField(choices=[('global', '全局角色'), ('company', '公司角色'), ('group', '集团角色')], default='company', max_length=20, verbose_name='角色范围'),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='organizations.company', verbose_name='主公司'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=50, verbose_name='角色代码'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, verbose_name='角色名称'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('company', 'code')},
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.CheckConstraint(condition=models.Q(('company__isnull', False), ('scope', 'global'), _negated=True), name='global_role_no_company'),
        ),
        migrations.AddField(
            model_name='usercompanymembership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='organizations.company', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='usercompanymembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='usercompanymembership',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_memberships', to='organizations.department', verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='usercompanymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='usercompanymembership',
            unique_together={('user', 'company', 'membership_type')},
        ),
    ]
