# Generated by Django 5.2.9 on 2026-01-08 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usercompanymembership_role_company_role_scope_and_more'),
        ('organizations', '0004_company_company_type_company_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asset_department',
            field=models.ForeignKey(blank=True, help_text='用户资产归属的部门，默认为主部门', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_employees', to='organizations.department', verbose_name='资产归属部门'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='用户的主要部门（可能属于多个部门）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.department', verbose_name='主部门'),
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主部门')),
                ('is_leader', models.BooleanField(default=False, verbose_name='是否部门负责人')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='部门内职位')),
                ('sso_order', models.IntegerField(default=0, help_text='从SSO平台同步的部门顺序，0表示主部门', verbose_name='SSO部门顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='organizations.department', verbose_name='部门')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户部门关联',
                'verbose_name_plural': '用户部门关联',
                'ordering': ['sso_order', 'created_at'],
                'unique_together': {('user', 'department')},
            },
        ),
    ]
