# Generated by Django 5.2.9 on 2026-01-06 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='报表名称')),
                ('code', models.CharField(max_length=50, verbose_name='报表代码')),
                ('report_type', models.CharField(choices=[('asset', '资产报表'), ('consumable', '耗材报表'), ('finance', '财务报表'), ('inventory', '盘点报表')], max_length=20, verbose_name='报表类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('columns', models.JSONField(default=list, verbose_name='列配置')),
                ('filters', models.JSONField(default=list, verbose_name='筛选条件')),
                ('grouping', models.JSONField(default=list, verbose_name='分组配置')),
                ('sorting', models.JSONField(default=list, verbose_name='排序配置')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统报表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='organizations.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '报表模板',
                'verbose_name_plural': '报表模板',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ReportExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=200, verbose_name='报表名称')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='文件路径')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('export_params', models.JSONField(default=dict, verbose_name='导出参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导出时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='organizations.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='导出人')),
                ('report_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttemplate', verbose_name='报表模板')),
            ],
            options={
                'verbose_name': '报表导出日志',
                'verbose_name_plural': '报表导出日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
