# Generated by Django 5.2.9 on 2026-01-06 05:58

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='公司代码')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='简称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='公司Logo')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='公司地址')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('website', models.URLField(blank=True, null=True, verbose_name='网站')),
                ('description', models.TextField(blank=True, null=True, verbose_name='公司简介')),
                ('wework_corp_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='企业微信CorpID')),
                ('dingtalk_corp_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='钉钉CorpID')),
                ('feishu_corp_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='飞书CorpID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('code', models.CharField(max_length=50, verbose_name='部门代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='部门描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('wework_dept_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='企业微信部门ID')),
                ('dingtalk_dept_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='钉钉部门ID')),
                ('feishu_dept_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='飞书部门ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.company', verbose_name='所属公司')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='部门负责人')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('create', '新建'), ('update', '修改'), ('delete', '删除'), ('move', '移动'), ('merge', '合并')], max_length=20, verbose_name='变更类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已拒绝'), ('processed', '已处理')], default='pending', max_length=20, verbose_name='状态')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='原数据')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='新数据')),
                ('description', models.TextField(blank=True, null=True, verbose_name='变更说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_changes_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='organizations.department', verbose_name='部门')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_changes_processed', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '组织异动',
                'verbose_name_plural': '组织异动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('code', models.CharField(max_length=50, verbose_name='区域代码')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='详细地址')),
                ('description', models.TextField(blank=True, null=True, verbose_name='区域描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organizations.company', verbose_name='所属公司')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.location', verbose_name='上级区域')),
            ],
            options={
                'verbose_name': '存放区域',
                'verbose_name_plural': '存放区域',
                'unique_together': {('company', 'code')},
            },
        ),
    ]
