# Generated by Django 5.2.9 on 2026-01-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_department_code_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dingtalk_corp_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='钉钉CorpID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='feishu_corp_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='飞书CorpID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wework_corp_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='企业微信CorpID'),
        ),
    ]
