# Generated by Django 5.2.9 on 2026-01-08 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assettransferitem_from_department_and_more'),
        ('organizations', '0003_alter_company_dingtalk_corp_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('group', '集团总部'), ('subsidiary', '子公司'), ('branch', '分公司'), ('affiliate', '关联公司'), ('dept_unit', '独立核算部门')], default='subsidiary', max_length=20, verbose_name='公司类型'),
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='CNY', max_length=10, verbose_name='核算货币'),
        ),
        migrations.AddField(
            model_name='company',
            name='fiscal_year_start',
            field=models.IntegerField(default=1, help_text='1-12', verbose_name='财年起始月'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='法人代表'),
        ),
        migrations.AddField(
            model_name='company',
            name='org_mode',
            field=models.CharField(choices=[('independent', '独立组织架构'), ('shared', '共享组织架构'), ('inherit', '继承上级架构')], default='independent', help_text='决定部门和用户的数据隔离方式', max_length=20, verbose_name='组织架构模式'),
        ),
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='用于集团公司层级管理', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.company', verbose_name='上级公司'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='税务登记号'),
        ),
        migrations.AlterField(
            model_name='company',
            name='dingtalk_corp_id',
            field=models.CharField(blank=True, help_text='[Deprecated] 请使用SSO配置管理', max_length=200, null=True, verbose_name='钉钉CorpID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='feishu_corp_id',
            field=models.CharField(blank=True, help_text='[Deprecated] 请使用SSO配置管理', max_length=200, null=True, verbose_name='飞书CorpID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wework_corp_id',
            field=models.CharField(blank=True, help_text='[Deprecated] 请使用SSO配置管理', max_length=200, null=True, verbose_name='企业微信CorpID'),
        ),
        migrations.CreateModel(
            name='CrossCompanyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(max_length=50, unique=True, verbose_name='调拨单号')),
                ('transfer_type', models.CharField(choices=[('transfer', '调拨'), ('lease', '租借'), ('allocation', '划拨'), ('sale', '销售')], default='transfer', max_length=20, verbose_name='调拨类型')),
                ('transfer_value', models.DecimalField(decimal_places=4, default=0, help_text='调拨资产的总价值', max_digits=19, verbose_name='调拨价值')),
                ('settlement_type', models.CharField(choices=[('internal', '内部划转'), ('cost_allocation', '费用分摊'), ('market_price', '市场定价'), ('book_value', '账面价值')], default='internal', max_length=20, verbose_name='结算方式')),
                ('settlement_amount', models.DecimalField(decimal_places=4, default=0, help_text='实际结算金额，可能与调拨价值不同', max_digits=19, verbose_name='结算金额')),
                ('settlement_date', models.DateField(blank=True, null=True, verbose_name='结算日期')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='调拨原因')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已审批'), ('in_transit', '调拨中'), ('completed', '已完成'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('from_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='调出审批时间')),
                ('to_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='调入审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_transfers_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('from_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_company_approvals', to=settings.AUTH_USER_MODEL, verbose_name='调出审批人')),
                ('from_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='organizations.company', verbose_name='调出公司')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_cross_transfers', to='organizations.department', verbose_name='调出部门')),
                ('to_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_company_approvals', to=settings.AUTH_USER_MODEL, verbose_name='调入审批人')),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='organizations.company', verbose_name='调入公司')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_cross_transfers', to='organizations.department', verbose_name='调入部门')),
            ],
            options={
                'verbose_name': '跨公司调拨',
                'verbose_name_plural': '跨公司调拨',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossCompanyTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='原值')),
                ('book_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='账面净值')),
                ('transfer_price', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='调拨价格')),
                ('asset_snapshot', models.JSONField(default=dict, help_text='资产在调拨时的完整信息快照', verbose_name='资产快照')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_company_transfers', to='assets.asset', verbose_name='资产')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organizations.crosscompanytransfer', verbose_name='调拨单')),
            ],
            options={
                'verbose_name': '跨公司调拨明细',
                'verbose_name_plural': '跨公司调拨明细',
                'unique_together': {('transfer', 'asset')},
            },
        ),
    ]
